import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

// Create Supabase client only if environment variables are available
const createSupabaseClient = () => {
  const supabaseUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseAnonKey = process.env.SUPABASE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  
  if (!supabaseUrl || !supabaseAnonKey) {
    console.warn('Supabase environment variables not found')
    return null
  }
  
  return createClient(supabaseUrl, supabaseAnonKey)
}

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params

    // Handle local drafts (demo mode)
    if (id.startsWith('local-')) {
      const demoContent = `Title: Demo Content\n\nThis is a demo content generated by the AI SEO Content Agent. The full content would be available here in a production environment.`
      
      const response = new NextResponse(demoContent)
      response.headers.set('Content-Type', 'text/plain')
      response.headers.set('Content-Disposition', `attachment; filename="demo-content.txt"`)
      
      return response
    }

    // Try to create Supabase client
    const supabase = createSupabaseClient()
    if (!supabase) {
      return NextResponse.json(
        { error: 'Database not configured' },
        { status: 503 }
      )
    }

    // Fetch the content draft
    const { data: draft, error } = await supabase
      .from('content_drafts')
      .select('title, content')
      .eq('id', id)
      .single()

    if (error || !draft) {
      return NextResponse.json(
        { error: 'Content not found' },
        { status: 404 }
      )
    }

    // Format the content for download
    const downloadContent = `Title: ${draft.title}\n\n${draft.content}`

    // Create response with file download headers
    const response = new NextResponse(downloadContent)
    response.headers.set('Content-Type', 'text/plain')
    response.headers.set('Content-Disposition', `attachment; filename="${draft.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt"`)

    return response
  } catch (error) {
    console.error('Download error:', error)
    return NextResponse.json(
      { error: 'Failed to download content' },
      { status: 500 }
    )
  }
} 